spring:
  thymeleaf:
    cache: false

  datasource:
    initialization-mode: never
    username: admin
    password: admin81990
    url: jdbc:mysql://book-store-db.csj4ekoy1mis.eu-north-1.rds.amazonaws.com:3306/book_store
    #platform: org.hibernate.dialect.H2Dialect
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql

  data:
    rest:
      base-path: "/api"
      detection-strategy: annotated

amazonProperties:
  accessKey: "ACCESS_AWS_KEY"
  secretKey: "SECRET_AWS_KEY"

amazonS3Properties:
  bucketName: "book-store-storage"

amazonSQSProperties:
  commentQueue: "CommentQueue"
  fixedDelay: "30000"